from read_pdb import *
import sys 
from Bio import SeqIO 
from Bio.Blast import NCBIWWW 


PDB = processPDB("2ocj", "/home/cquiroz/Escritorio/tesis/", "2ocj.pdb", "/home/cquiroz/Escritorio/tesis/")
PDB.getAllResiduesPDB()


result_handle = NCBIWWW.qblast("blastp", "nr", "LCLYTHIGRNIYYGSYLYSETWNTGIMLLLITMATAFMGYVLPWGQMSFWGATVITNLFSAIPYIGTNLVEWIWGGFSVDKATLNRFFAFHFILPFTMVALAGVHLTFLHETGSNNPLGLTSDSDKIPFHPYYTIKDFLGLLILILLLLLLALLSPDMLGDPDNHMPADPLNTPLHIKPEWYFLFAYAILRSVPNKLGGVLALFLSIVILGLMPFLHTSKHRSMMLRPLSQALFWTLTMDLLTLTWIGSQPVEYPYTIIGQMASILYFSIILAFLPIAGXIENY", format_type="Text") 
print(result_handle.read())